language: node_js
node_js:
  - "4.1"
sudo: required
services: docker
install:
 - npm install jshint -g
env:
 matrix:
   - MONGODB_VERSION=2.4
   - MONGODB_VERSION=2.6
   - MONGODB_VERSION=2.8
   - MONGODB_VERSION=3.0
   - MONGODB_VERSION=3.2
script:
 - jshint variety.js
 - ./test.sh